version: '3.8'
services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - app
    environment:
      - REDIS_REPLICATION_MODE=master
    command: ['redis-server', '--bind', 'redis', '--port', '6379']

  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5433:5432
    networks:
      - app
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-task

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    networks:
      - app
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
    env_file:
      - .env
    command: yarn start:prod

networks:
  app:
    name: test-network
